export const logo = require('./Logo_alta.svg');
export const device = require('./device.svg');
export const report = require('./report.svg');
export const service = require('./Frame 332.svg');
export const setting = require('./setting.svg');
export const logout = require('./logout.svg');
export const provideNumber = require('./provide-number.svg');
export const bell = require('./bell.svg');
export const numberOrder = require('./numberOrde.svg');
export const numberOrdered = require('./numberOrdered.svg');
export const numberOrderWaiting = require('./numberOrderWaiting.svg');
export const numberOrderSkip = require('./numberOrderSkip.svg')
